In [2]:
import pandas as pd

# Load data
df = pd.read_csv("monthly_avg_price.csv")  # change name if needed
df.head()

  month_year                       product  store_id COICOP5 COICOP4  price
0    2020-12  abate arg biologico 600.0 gr         6   Pears   Fruit   2.98
1    2020-12  abate arg biologico 600.0 gr         7   Pears   Fruit   2.98
2    2020-12  abate arg biologico 600.0 gr        10   Pears   Fruit   2.98
3    2020-12  abate arg biologico 600.0 gr        15   Pears   Fruit   2.98
4    2020-12  abate arg biologico 600.0 gr        16   Pears   Fruit   2.98

In [4]:
import numpy as np

np.random.seed(42)  # for reproducibility

# Let's assume your price column is called 'price'
# We'll create quantities inversely related to price
max_price = df['price'].max()
min_price = df['price'].min()

# Scale prices to 0â€“1 range
price_scaled = (df['price'] - min_price) / (max_price - min_price)

# Higher price = lower quantity, add some randomness
df['quantity'] = (1 - price_scaled) * np.random.randint(20, 800, size=len(df))

# Ensure no zero quantities
df['quantity'] = df['quantity'].clip(lower=1).astype(int)
df.head()

,month_year,product,store_id,COICOP5,COICOP4,price,quantity
0,2020-12,abate arg biologico 600.0 gr,6,Pears,Fruit,2.98,117
1,2020-12,abate arg biologico 600.0 gr,7,Pears,Fruit,2.98,439
2,2020-12,abate arg biologico 600.0 gr,10,Pears,Fruit,2.98,280
3,2020-12,abate arg biologico 600.0 gr,15,Pears,Fruit,2.98,121
4,2020-12,abate arg biologico 600.0 gr,16,Pears,Fruit,2.98,87

In [ ]:
df.to_csv("monthly_with_qty.csv", index=False)